import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import "../shared/styles/globals.css";
import Providers from "@/shared/utils/providers";

import localFont from "next/font/local";

const clashDisplay = localFont({
  src: "../assets/fonts/ClashDisplay-Variable.ttf",
  variable: "--font-clashDisplay",
  weight: "700",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={clashDisplay.variable}>
        <Providers>
           {children}
        </Providers>
      </body>
    </html>
    </ClerkProvider>
  );
}
